#!/bin/bash
MAX_BRIGHTNESS=1.0
MIN_BRIGHTNESS=0.2
CURRENT=$(xrandr --current --verbose | grep Brightness | awk 'NR==1{print$2}')
DEFAULT=1.0
MONITOR=LVDS-1
DunstNotify(){
	message=$1
	icon="/usr/share/icons/Adwaita/scalable/status/weather-clear-symbolic.svg"
	pkill dunst
	notify-send -t 1000 -i $icon "$message"
}
XrandrCmd(){
	xrandr --output $MONITOR --brightness $brightness && DunstNotify "Changing brightness to $brightness"
}
IncreaseBrightness(){
	brightness=$(echo "scale=1;$CURRENT+0.1" | bc | sed 's/^\./0./')
	if [[ $brightness > $MAX_BRIGHTNESS ]]; then
		DunstNotify "Max Brightness reached"
		return
	fi
	XrandrCmd
}
DecreaseBrightness(){
	brightness=$(echo "scale=1;$CURRENT-0.1" | bc | sed 's/^\./0./')
	if [[ $brightness < $MIN_BRIGHTNESS ]]; then
		DunstNotify "Min Brightness reached"
		return
	fi
	XrandrCmd
}
DefaultBrightness(){
	brightness=$DEFAULT
	XrandrCmd && DunstNotify "Default Brightness"
}

case $1 in 
	"--increase")
		IncreaseBrightness
		;;
	"--decrease")
		DecreaseBrightness
		;;
	"--default")
		DefaultBrightness
		;;
	*)
		echo -e "Usage:\n\t--increase: Increase brightness\n\t--decrease: Decrease brightness\n\t--default: Change to default brightness"
		;;
esac