#!/bin/bash
FILE_NAME='%d-%m-%Y-%H:%M:%S_$wx$h'
FILE_EXT=".png"
ssCheck(){
	if [ -e $1 ]; then
		mv $1 ~/Pictures
		notify-send -t 5000 -i ~/Pictures/$1 'Screenshot' $1
	else
		notify-send -u critical -t 5000 'Screenshot' 'Something went wrong durin the screenshot'
	fi
}
scrotFull(){
	ssName=$(scrot "ss_${FILE_NAME}${FILE_EXT}" -e 'echo $f')
	ssCheck $ssName
}
scrotPartial(){
	notify-send "Select the are to be taken the screenshot"
	ssName=$(scrot -s "ss_${FILE_NAME}_partial${FILE_EXT}" -e 'echo $f')
	ssCheck $ssName
}
scrotCurrent(){
	ssName=$(scrot -u "ss_${FILE_NAME}_current${FILE_EXT}" -e 'echo $f')
	ssCheck $ssName
}
case $1 in 
	"--partial")
		scrotPartial
		;;
	"--current")
		scrotCurrent
		;;
	*)
		scrotFull
		;;
esac